mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
enableMavenTestStage: false
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11